{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ui.hostName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ui.hostName" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60
{{- end }}
{{- if .Values.dashboard.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ui.dashboardName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ui.dashboardName" . }}
  minReplicas: {{ .Values.dashboard.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.dashboard.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.dashboard.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- if .Values.vpc.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ui.vpcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ui.vpcName" . }}
  minReplicas: {{ .Values.vpc.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.vpc.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.vpc.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- if .Values.iam.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ui.iamName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ui.iamName" . }}
  minReplicas: {{ .Values.iam.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.iam.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.iam.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
